version: "2"
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
#     - ./share/grafana:/usr/share/grafana
      - data:/var/lib/grafana
    ports:
    - "3000:3000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     - ./share/prometheus:/usr/share/prometheus
      - data:/prometheus
    ports:
    - "9090:9090"
volumes:
  data:
