version: "2"
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./var/lib/grafana:/var/lib/grafana
      - ./etc/grafana:/etc/grafana
    ports:
    - "3000:3000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./etc/prometheus:/etc/prometheus
      - ./var/lib/prometheus:/var/lib/prometheus
    ports:
    - "9090:9090"
