global:
  scrape_interval: 15s
  evaluation_interval: 30s
  external_labels:
    monitor: performance
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
          - "localhost:9100"
