version: "2"
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
#     - ./share/grafana:/usr/share/grafana
      - data:/var/lib/grafana
    ports:
    - "3000:3000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     - ./share/prometheus:/usr/share/prometheus
      - data:/prometheus
    ports:
    - "9090:9090"
  etcd:
    image: quay.io/coreos/etcd:v3.2
    restart: always
    command: [
        "/usr/local/bin/etcd",
        "--name", "my-etcd-1",
        "--data-dir", "/etcd-data",
        "--listen-client-urls", "http://localhost:2379",
        "--advertise-client-urls", "http://localhost:2379",
        "--listen-peer-urls", "http://localhost:2380",
        "--initial-advertise-peer-urls", "http://localhost:2380",
        "--initial-cluster", "my-etcd-1=http://localhost:2380",
        "--initial-cluster-token", "my-etcd-token",
        "--initial-cluster-state", "new",
        "--auto-compaction-retention", "1"
      ]
    volumes:
      - data:/etcd-data
    ports:
    - "2379:2379"
    - "2380:2380"
volumes:
  data:
