version: "2"
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  node:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=test
      - PORT=3000
