global:
  scrape_interval: 10s
  scrape_timeout: 10s
  external_labels:
    monitor: 'metrics'
scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: [':9100']
